# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://humingk.github.io
date_format: "ordinal"
title: 小明也来过的技术博客
subtitle: "这个人很写，什么也没有懒"
description: ""
keywords: humingk
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: humingk
organization: 
organization_url: 
github_username: humingk
location: Beijing, China
email: humingk@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 6
lsi: false
quiet: false
excerpt_separator: "\n\n"
# permalink: /:year/:month/:day/:title/
permalink: /:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: humingk/humingk.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
gitalk:
    owner: humingk
    repo: humingk.github.io
    clientID: c0b56c40d5e39f713f9a
    clientSecret: 3633016d9a54d80cd120ed77c12e527af18d6087

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 8

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
